# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - mk2_arm_controller

  mk2_arm_controller:
    type: FollowJointTrajectory
    joints:
      - pitch_joint_1
      - roll_joint_2
      - pitch_joint_3
      - roll_joint_4
      - pitch_joint_5
      - roll_joint_6
    action_ns: follow_joint_trajectory