# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mk2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mk2_arm_controller:
  ros__parameters:
    joints:
      - pitch_joint_1
      - roll_joint_2
      - pitch_joint_3
      - roll_joint_4
      - pitch_joint_5
      - roll_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true